USE letter_game_db;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(128) NOT NULL UNIQUE,
  email VARCHAR(128) NOT NULL UNIQUE,
  password VARCHAR(256) NOT NULL,
  role ENUM('ADMIN', 'PLAYER') NOT NULL DEFAULT 'PLAYER',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS games (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  words JSON NOT NULL,
  round INTEGER NOT NULL,
  first_user_id INTEGER NOT NULL,
  second_user_id INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS scores (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  score INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  game_id INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dictionary_whitelist (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  word VARCHAR(128) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS dictionary_blacklist (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  word VARCHAR(128) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

-- opcionális audit
CREATE TABLE IF NOT EXISTS dictionary_audit (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  word VARCHAR(128) NOT NULL,
  proper_candidate INTEGER NOT NULL DEFAULT 0,
  result ENUM('ok','whitelist','blacklist','hunspell','chars','proper','too_short') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (created_at),
  INDEX (word)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;
