USE letter_game_db;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS board_cells;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS round_tiles;
DROP TABLE IF EXISTS rounds;
DROP TABLE IF EXISTS game_players;
DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS games;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE games (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  status ENUM('CREATED', 'ROUND_ACTIVE', 'FINISHED') NOT NULL DEFAULT 'CREATED',
  round INTEGER NOT NULL DEFAULT 0,
  max_rounds INTEGER NOT NULL DEFAULT 7,
  first_user_id INTEGER NOT NULL,
  second_user_id INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMP NULL DEFAULT NULL,
  finished_at TIMESTAMP NULL DEFAULT NULL,
  FOREIGN KEY (first_user_id) REFERENCES users(id),
  FOREIGN KEY (second_user_id) REFERENCES users(id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

CREATE TABLE game_players (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  game_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  player_order INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE (game_id, user_id),
  UNIQUE (game_id, player_order)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

CREATE TABLE boards (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  game_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE (game_id, user_id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

CREATE TABLE board_cells (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  game_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  letter VARCHAR(8) NOT NULL,
  points INTEGER NOT NULL DEFAULT 10,
  is_joker BOOLEAN NOT NULL DEFAULT FALSE,
  source ENUM('TITLE', 'PLAYER', 'JOKER') NOT NULL,
  locked BOOLEAN NOT NULL DEFAULT TRUE,
  created_round INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE (game_id, user_id, x, y)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

CREATE TABLE rounds (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  game_id INTEGER NOT NULL,
  round_number INTEGER NOT NULL,
  status ENUM('ACTIVE', 'CLOSED') NOT NULL DEFAULT 'ACTIVE',
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ended_at TIMESTAMP NULL DEFAULT NULL,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  UNIQUE (game_id, round_number)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

CREATE TABLE round_tiles (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  game_id INTEGER NOT NULL,
  round_number INTEGER NOT NULL,
  tile_id CHAR(36) NOT NULL,
  letter VARCHAR(8) NOT NULL,
  points INTEGER NOT NULL,
  is_joker BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  UNIQUE (game_id, round_number, tile_id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

CREATE TABLE scores (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  score INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  game_id INTEGER NOT NULL,
  round_number INTEGER,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;
