USE letter_game_db;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS moves;
DROP TABLE IF EXISTS board_cells;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS round_tiles;
DROP TABLE IF EXISTS rounds;
DROP TABLE IF EXISTS game_players;
DROP TABLE IF EXISTS games;

SET FOREIGN_KEY_CHECKS = 1;